FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

LABEL org.opencontainers.image.source=https://github.com/tenstorrent/tt-forge-onnx
LABEL org.opencontainers.image.licenses=Apache-2.0

# Install system tools
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y \
    wget \
    curl \
    git \
    jq \
    unzip \
    ca-certificates

# Install Python 3.12
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.12 python3.12-dev python3.12-venv python3.12-distutils

COPY *.whl /tmp/
RUN pip install --no-cache-dir /tmp/*.whl --break-system-packages && \
    rm -rf /tmp/*.whl

CMD ["/bin/bash"]
