FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

LABEL org.opencontainers.image.source=https://github.com/tenstorrent/tt-forge-onnx
LABEL org.opencontainers.image.licenses=Apache-2.0

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Install system tools
RUN apt-get update && \
    apt-get install -y \
    wget \
    curl \
    git \
    jq \
    unzip \
    ca-certificates \
    software-properties-common

# Install Python 3.12
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.12 python3.12-dev python3.12-venv python3-pip && \
    python3.12 -m ensurepip --upgrade && \
    python3.12 -m pip install --upgrade pip setuptools wheel --break-system-packages

COPY *.whl /tmp/
RUN python3.12 -m pip install --only-binary=:all: --no-cache-dir /tmp/*.whl --break-system-packages && \
    rm -rf /tmp/*.whl

CMD ["/bin/bash"]
