name: Manual release tests

on:
  workflow_dispatch:

permissions:
  actions: write
  id-token: write
  packages: write
  checks: write
  contents: write

jobs:
  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    name: "Build tt-forge-onnx"
    secrets: inherit
    needs: docker-build
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      build: Release

  build-and-test-release-docker:
    uses: ./.github/workflows/call-build-and-test-release-docker.yml
    needs: [ build ]
    secrets: inherit
    with:
      wheel_release_artifact_run_id: ${{ needs.build.outputs.run_id }}
      wheel_release_artifact_name: forge-wheel
