# Daily uplift of the tt-mlir submodule to origin/main.

name: Nightly Uplift MLIR

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 08:00 UTC every day
  workflow_dispatch:  # Manual trigger

jobs:
  uplift-tt-mlir:
    uses: ./.github/workflows/call-uplift-submodule.yml
    with:
      submodule_path: third_party/tt-mlir
      submodule_version: origin/main
      pr_branch: uplift-tt-mlir
      upstream_repo: tenstorrent/tt-mlir
    secrets: inherit
